#cloud-config
package_update: true
bootcmd:
  - mkdir -p /etc/blobfuse2
write_files:
%{ for storage_account, registry_storage_mount in registry_storage_mounts ~}
  - path: /etc/blobfuse2/${storage_account}.yaml
    permissions: "0600"
    owner: root:root
    content: |
      version: 2
      logging:
        type: syslog
        level: log_warning
      components:
        - libfuse
        - attr_cache
        - azstorage
      libfuse:
        attribute-expiration-sec: 120
        entry-expiration-sec: 120
        negative-entry-expiration-sec: 120
      attr_cache:
        timeout-sec: 120
      azstorage:
        type: block
        account-name: ${storage_account}
        container: ${registry_storage_mount.container_name}
        endpoint: https://${storage_account}.blob.core.windows.net
        mode: msi
%{ endfor ~}
runcmd:
  - bash -lc '. /etc/os-release; curl -fsSL "https://packages.microsoft.com/config/debian/$VERSION_ID/packages-microsoft-prod.deb" -o /tmp/packages-microsoft-prod.deb'
  - |
    echo "==== Adding windows packages list ..."
    apt-get -o DPkg::Lock::Timeout=60 install -y /tmp/packages-microsoft-prod.deb
  - |
    echo "==== apt update ..."
    apt-get -o DPkg::Lock::Timeout=60 update
  - |
    echo "==== apt install ..."
    apt-get -o DPkg::Lock::Timeout=60 install -y blobfuse2 fuse3 libfuse3-dev
%{ for storage_account, registry_storage_mount in registry_storage_mounts ~}
  - mkdir -p ${registry_storage_mount.cache_path}
  - mkdir -p ${registry_storage_mount.mount_path}
  - grep -q "^blobfuse2 ${registry_storage_mount.mount_path} " /etc/fstab || echo "blobfuse2 ${registry_storage_mount.mount_path} fuse3 defaults,_netdev,--config-file=/etc/blobfuse2/${storage_account}.yaml,--tmp-path=${registry_storage_mount.cache_path},${registry_storage_mount.blobfuse_option} 0 0" >> /etc/fstab
%{ endfor ~}
  - mount -a
